export const NEWS: Record<string, string> = {
  rural:
    "Your hospital opens in a rural community — primary provider for 50 miles.",
  suburban: "Located in a booming suburban corridor.",
  urban: "In the metro, serving diverse communities.",
  nonprofit: "Non-profit board balances mission with sustainability.",
  forprofit: "Investors expect discipline.",
  government: "County charter signed. The safety net.",
  small: "75 beds — lean and focused.",
  medium: "200 beds: the community workhorse.",
  large: "400 beds at regional referral scale.",
  major: "650 beds. Building an institution.",
  teaching: "Teaching programs attract top residents.",
  procedural: "Surgical investment pays off.",
  community: "Community programs build trust.",
  safety_net: "DSH payments offset the payer mix.",
  employ: "Physician employment unlocks CDI.",
  contract: "Contract groups: predictable costs.",
  independent: "Independent physicians; coordination difficult.",
  cardio: "Heart and joint programs attract referrals.",
  cancer: "Cancer center becomes a magnet.",
  behav: "Behavioral health cuts ED psych holds 40%.",
  maintain: "Operational excellence compounds.",
  own_asc: "ASC network captures volume.",
  jv_asc: "Physician JV aligns incentives.",
  hopd: "HOPD rates favorable. Reform looms.",
  agg_comm: "Premium rates; two payers drop you.",
  ma: "MA volume surges.",
  vbc: "Value-based contracts reward quality.",
  premium: "Best workplace. Travel spend drops 60%.",
  lean: "Costs controlled; turnover accelerates.",
  train: "Nursing academy graduates stay.",
  ehr: "EHR: painful then transformative.",
  ai: "AI CDI catches gaps. Sepsis alerts save lives.",
  tele: "Virtual visits extend reach.",
  min: "Holding tech line; competitors ahead.",
  acquire: "Acquisition doubles presence.",
  merge: "System affiliation drops supply costs 8%.",
  divest: "Shedding underperformers improves costs.",
  organic: "Quality drives sustainable growth.",
  tower: "New tower opens to fanfare.",
  ambnet: "Five outpatient locations create funnel.",
  debt: "Bond upgrade. Savings compound.",
};
