import type { Phase } from "../model/types";

export const PHASES: Phase[] = [
  {
    phase: 0,
    title: "Choose Your Market",
    subtitle: "Location and ownership shape everything.",
    decisions: [
      {
        id: "location",
        title: "Location",
        description: "Your market shapes payer mix, competition, and costs.",
        options: [
          {
            id: "rural",
            label: "Rural Community",
            icon: "🌾",
            desc: "Aging population. Dominant but heavy Medicare, thin commercial.",
            effects: {
              commercial_share: 0.15,
              medicare_share: 0.45,
              ma_share: 0.08,
              medicaid_share: 0.18,
              self_pay_share: 0.14,
              market_share: 0.42,
              fixed_costs: 10000000,
              commercial_mult: 1.6,
              base_cost_per_case: "mult:0.85",
              other_revenue: "add:2000000",
              community_benefit: 65,
              patient_satisfaction: 55,
            },
          },
          {
            id: "suburban",
            label: "Suburban Growth",
            icon: "🏘️",
            desc: "Young families, employer insurance. Strong commercial, rising competition.",
            effects: {
              commercial_share: 0.44,
              medicare_share: 0.2,
              ma_share: 0.08,
              medicaid_share: 0.16,
              self_pay_share: 0.12,
              market_share: 0.24,
              fixed_costs: 20000000,
              commercial_mult: 2.3,
              community_benefit: 45,
              patient_satisfaction: 52,
            },
          },
          {
            id: "urban",
            label: "Urban Metro",
            icon: "🏙️",
            desc: "Diverse. Higher Medicaid/uninsured, large volumes, intense competition.",
            effects: {
              commercial_share: 0.3,
              medicare_share: 0.22,
              ma_share: 0.12,
              medicaid_share: 0.26,
              self_pay_share: 0.1,
              market_share: 0.12,
              fixed_costs: 26000000,
              commercial_mult: 2.5,
              base_cost_per_case: "mult:1.05",
              other_revenue: "add:3000000",
              community_benefit: 55,
              patient_satisfaction: 42,
            },
          },
        ],
      },
      {
        id: "ownership",
        title: "Ownership",
        description: "Governance defines incentives, capital, and culture.",
        options: [
          {
            id: "nonprofit",
            label: "Non-Profit",
            icon: "🏥",
            desc: "Tax-exempt, philanthropy. Mission-driven.",
            effects: {
              other_revenue: "add:4000000",
              efficiency_mult: "mult:1.01",
              quality_score: "add:5",
              community_benefit: "add:10",
            },
          },
          {
            id: "forprofit",
            label: "For-Profit",
            icon: "📈",
            desc: "Shareholder-driven, disciplined costs.",
            effects: {
              efficiency_mult: "mult:0.97",
              quality_score: "add:-3",
              community_benefit: "add:-10",
            },
          },
          {
            id: "government",
            label: "Government",
            icon: "🏛️",
            desc: "Safety net with appropriations.",
            effects: {
              medicaid_share: "add:0.10",
              commercial_share: "add:-0.08",
              self_pay_share: "add:0.03",
              other_revenue: "add:20000000",
              efficiency_mult: "mult:1.05",
              quality_score: "add:-5",
              community_benefit: "add:20",
              market_share: "add:0.03",
            },
          },
        ],
      },
    ],
  },
  {
    phase: 1,
    title: "Build Your Foundation",
    subtitle: "Scale and strategy for Year 1",
    decisions: [
      {
        id: "size",
        title: "Hospital Size",
        description: "Scale drives volume, services, and fixed costs.",
        options: [
          {
            id: "small",
            label: "Small (75 beds)",
            icon: "🏠",
            desc: "Critical access. Low overhead, limited services.",
            effects: {
              beds: 75,
              fixed_costs: "mult:0.50",
              cmi: 1.2,
              outpatient_ratio: 0.25,
              quality_score: "add:-5",
            },
          },
          {
            id: "medium",
            label: "Medium (200 beds)",
            icon: "🏢",
            desc: "Community hospital. Core services.",
            effects: { beds: 200, cmi: 1.5, outpatient_ratio: 0.35 },
          },
          {
            id: "large",
            label: "Large (400 beds)",
            icon: "🏗️",
            desc: "Regional center. Full services.",
            effects: {
              beds: 400,
              fixed_costs: "mult:1.90",
              cmi: 1.8,
              outpatient_ratio: 0.4,
              quality_score: "add:5",
              occupancy_rate: "add:0.03",
            },
          },
          {
            id: "major",
            label: "Major (650 beds)",
            icon: "🏰",
            desc: "Tertiary center. Maximum complexity.",
            effects: {
              beds: 650,
              fixed_costs: "mult:3.20",
              cmi: 2.2,
              outpatient_ratio: 0.45,
              quality_score: "add:10",
              occupancy_rate: "add:0.06",
              base_cost_per_case: "mult:1.12",
            },
          },
        ],
      },
      {
        id: "strategy",
        title: "Strategic Focus",
        description: "What defines your competitive advantage?",
        options: [
          {
            id: "teaching",
            label: "Teaching & Research",
            icon: "🎓",
            desc: "Academic mission. GME/IME, grants. Highest quality + costs.",
            effects: {
              teaching_revenue: "add:25000000",
              cmi: "add:0.12",
              quality_score: "add:15",
              base_cost_per_case: "mult:1.15",
              fixed_costs: "mult:1.25",
              readmission_rate: "add:-0.02",
              market_share: "add:0.04",
            },
          },
          {
            id: "procedural",
            label: "Procedural Excellence",
            icon: "🔬",
            desc: "High-margin surgical specialties.",
            effects: {
              cmi: "add:0.08",
              commercial_mult: "add:0.06",
              base_cost_per_case: "mult:1.06",
              quality_score: "add:8",
              avg_los: "add:-0.3",
              market_share: "add:0.02",
            },
          },
          {
            id: "community",
            label: "Community Care",
            icon: "❤️",
            desc: "Primary/preventive. Strong loyalty, lower readmissions.",
            effects: {
              readmission_rate: "add:-0.03",
              patient_satisfaction: "add:12",
              community_benefit: "add:15",
              base_cost_per_case: "mult:0.98",
              market_share: "add:0.03",
              quality_score: "add:5",
            },
          },
          {
            id: "safety_net",
            label: "Safety Net",
            icon: "🛡️",
            desc: "Serve the underserved. DSH and grants offset payer mix.",
            effects: {
              medicaid_share: "add:0.08",
              self_pay_share: "add:0.04",
              commercial_share: "add:-0.08",
              other_revenue: "add:12000000",
              community_benefit: "add:25",
              quality_score: "add:3",
              readmission_rate: "add:0.01",
            },
          },
        ],
      },
    ],
  },
  {
    phase: 2,
    title: "Year 2 — Physicians & Services",
    subtitle: "Organize medical staff and invest.",
    decisions: [
      {
        id: "phys",
        title: "Physician Alignment",
        description:
          "Doctor relationships drive quality, documentation, referrals.",
        options: [
          {
            id: "employ",
            label: "Employ Physicians",
            icon: "👔",
            desc: "Control practice patterns, CDI. Subsidy ~$317K/FTE.",
            effects: {
              fixed_costs: "mult:1.12",
              quality_score: "add:8",
              cmi: "add:0.03",
              readmission_rate: "add:-0.01",
              avg_los: "add:-0.2",
              efficiency_mult: "mult:0.985",
            },
          },
          {
            id: "contract",
            label: "Contract Groups",
            icon: "📋",
            desc: "Predictable costs, less alignment.",
            effects: {
              fixed_costs: "mult:1.04",
              efficiency_mult: "mult:1.01",
              quality_score: "add:2",
              patient_satisfaction: "add:-5",
            },
          },
          {
            id: "independent",
            label: "Independent Staff",
            icon: "🤝",
            desc: "Lowest cost, lowest control.",
            effects: {
              quality_score: "add:-3",
              market_share: "add:-0.02",
              efficiency_mult: "mult:0.99",
              patient_satisfaction: "add:3",
              readmission_rate: "add:0.01",
            },
          },
        ],
      },
      {
        id: "svc",
        title: "Service Line Investment",
        description: "Where you invest defines cases and margin.",
        options: [
          {
            id: "cardio",
            label: "Cardiology & Ortho",
            icon: "💓",
            desc: "Highest-margin procedural lines.",
            effects: {
              cmi: "add:0.05",
              commercial_mult: "add:0.04",
              base_cost_per_case: "mult:1.04",
              fixed_costs: "add:6000000",
              market_share: "add:0.02",
              avg_los: "add:-0.2",
            },
          },
          {
            id: "cancer",
            label: "Cancer Center",
            icon: "🎗️",
            desc: "Referral magnet. Enormous capital.",
            effects: {
              cmi: "add:0.06",
              fixed_costs: "add:12000000",
              outpatient_ratio: "add:0.04",
              market_share: "add:0.04",
              quality_score: "add:6",
              patient_satisfaction: "add:5",
            },
          },
          {
            id: "behav",
            label: "Behavioral Health",
            icon: "🧠",
            desc: "Massive unmet demand. Cuts readmissions.",
            effects: {
              community_benefit: "add:18",
              readmission_rate: "add:-0.02",
              quality_score: "add:4",
              patient_satisfaction: "add:8",
              fixed_costs: "add:3000000",
              market_share: "add:0.02",
            },
          },
          {
            id: "maintain",
            label: "Maintain Mix",
            icon: "⚖️",
            desc: "Operational improvement focus.",
            effects: {
              efficiency_mult: "mult:0.985",
              fixed_costs: "add:-1000000",
            },
          },
        ],
      },
    ],
  },
  {
    phase: 3,
    title: "Year 3 — Ambulatory & Payer",
    subtitle: "Outpatient growing 2× faster than inpatient.",
    decisions: [
      {
        id: "amb",
        title: "Ambulatory Strategy",
        description: "HOPDs pay ~1.8× ASCs but cost 42% more.",
        options: [
          {
            id: "own_asc",
            label: "Build Owned ASCs",
            icon: "🏥",
            desc: "Lower cost at ASC rates.",
            effects: {
              outpatient_ratio: "add:0.06",
              base_cost_per_case: "mult:0.97",
              fixed_costs: "add:5000000",
              efficiency_mult: "mult:0.985",
              market_share: "add:0.02",
            },
          },
          {
            id: "jv_asc",
            label: "JV with Physicians",
            icon: "🤝",
            desc: "Shared ownership, aligned incentives.",
            effects: {
              outpatient_ratio: "add:0.05",
              market_share: "add:0.04",
              patient_satisfaction: "add:5",
              quality_score: "add:3",
              fixed_costs: "add:2500000",
            },
          },
          {
            id: "hopd",
            label: "Double Down HOPD",
            icon: "🏗️",
            desc: "Higher rates today. Reform risk.",
            effects: {
              outpatient_ratio: "add:0.05",
              commercial_mult: "add:0.03",
            },
          },
        ],
      },
      {
        id: "payer",
        title: "Payer Strategy",
        description: "Commercial rates = #1 margin driver.",
        options: [
          {
            id: "agg_comm",
            label: "Aggressive Rates",
            icon: "💰",
            desc: "Leverage position. Risk exclusion.",
            effects: {
              commercial_mult: "add:0.05",
              market_share: "add:-0.02",
              patient_satisfaction: "add:-3",
            },
          },
          {
            id: "ma",
            label: "Pursue MA",
            icon: "📑",
            desc: "Growing volume, lower pay.",
            effects: {
              ma_share: "add:0.06",
              medicare_share: "add:-0.04",
              ma_mult: "add:0.05",
              occupancy_rate: "add:0.03",
              efficiency_mult: "mult:1.01",
            },
          },
          {
            id: "vbc",
            label: "Value-Based Risk",
            icon: "🎯",
            desc: "Shared savings. High upside.",
            effects: {
              readmission_rate: "add:-0.02",
              quality_score: "add:8",
              efficiency_mult: "mult:0.98",
              fixed_costs: "add:3000000",
              community_benefit: "add:8",
            },
          },
        ],
      },
    ],
  },
  {
    phase: 4,
    title: "Year 4 — Workforce & Technology",
    subtitle: "Labor is 56% of costs.",
    decisions: [
      {
        id: "staff",
        title: "Staffing",
        description: "Contract labor costs industry $51B/year.",
        options: [
          {
            id: "premium",
            label: "Premium Wages",
            icon: "💎",
            desc: "Above-market. Reduces agency spend.",
            effects: {
              labor_mult: "mult:1.10",
              quality_score: "add:10",
              patient_satisfaction: "add:10",
              readmission_rate: "add:-0.015",
              efficiency_mult: "mult:0.98",
              market_share: "add:0.02",
            },
          },
          {
            id: "lean",
            label: "Lean + Travelers",
            icon: "✈️",
            desc: "Lower fixed cost, inconsistent quality.",
            effects: {
              labor_mult: "mult:0.93",
              fixed_costs: "mult:0.95",
              quality_score: "add:-8",
              patient_satisfaction: "add:-10",
              readmission_rate: "add:0.02",
              efficiency_mult: "mult:1.02",
            },
          },
          {
            id: "train",
            label: "Training Programs",
            icon: "📚",
            desc: "Build pipelines. Long payoff.",
            effects: {
              fixed_costs: "add:4000000",
              quality_score: "add:6",
              teaching_revenue: "add:3000000",
              patient_satisfaction: "add:5",
              readmission_rate: "add:-0.01",
            },
          },
        ],
      },
      {
        id: "tech",
        title: "Technology",
        description: "Expensive but potentially transformative.",
        options: [
          {
            id: "ehr",
            label: "EHR Overhaul",
            icon: "💻",
            desc: "Unified platform. Long-term gains.",
            effects: {
              fixed_costs: "add:15000000",
              efficiency_mult: "mult:0.97",
              quality_score: "add:6",
              avg_los: "add:-0.15",
              readmission_rate: "add:-0.01",
            },
          },
          {
            id: "ai",
            label: "AI Decision Support",
            icon: "🤖",
            desc: "CDI, sepsis, coding. CMI boost.",
            effects: {
              cmi: "add:0.04",
              fixed_costs: "add:5000000",
              quality_score: "add:4",
              avg_los: "add:-0.1",
              admin_mult: "mult:0.92",
            },
          },
          {
            id: "tele",
            label: "Telehealth",
            icon: "📱",
            desc: "Virtual visits. Extends reach.",
            effects: {
              outpatient_ratio: "add:0.03",
              patient_satisfaction: "add:7",
              community_benefit: "add:10",
              fixed_costs: "add:2000000",
              market_share: "add:0.02",
            },
          },
          {
            id: "min",
            label: "Minimal Tech",
            icon: "📄",
            desc: "Keep current. Risk falling behind.",
            effects: {
              quality_score: "add:-4",
              efficiency_mult: "mult:1.01",
              patient_satisfaction: "add:-3",
            },
          },
        ],
      },
    ],
  },
  {
    phase: 5,
    title: "Year 5 — Growth & Capital",
    subtitle: "Secure the future.",
    decisions: [
      {
        id: "growth",
        title: "Growth Strategy",
        description: "Consolidation and rationalization.",
        options: [
          {
            id: "acquire",
            label: "Acquire",
            icon: "🏗️",
            desc: "Expand overnight. Integration risk.",
            effects: {
              beds: "add:120",
              market_share: "add:0.10",
              fixed_costs: "mult:1.40",
              base_cost_per_case: "mult:1.03",
              occupancy_rate: "add:-0.05",
              quality_score: "add:-3",
            },
          },
          {
            id: "merge",
            label: "Join System",
            icon: "🔗",
            desc: "Purchasing power. Lose autonomy.",
            effects: {
              base_cost_per_case: "mult:0.93",
              commercial_mult: "add:0.04",
              efficiency_mult: "mult:0.97",
              fixed_costs: "mult:0.92",
              quality_score: "add:5",
            },
          },
          {
            id: "divest",
            label: "Divest",
            icon: "✂️",
            desc: "Improve margins, shrink footprint.",
            effects: {
              beds: "mult:0.80",
              fixed_costs: "mult:0.78",
              market_share: "add:-0.04",
              cmi: "add:0.03",
              efficiency_mult: "mult:0.97",
              community_benefit: "add:-10",
            },
          },
          {
            id: "organic",
            label: "Organic Growth",
            icon: "🌱",
            desc: "Quality and reputation.",
            effects: {
              quality_score: "add:5",
              patient_satisfaction: "add:5",
              market_share: "add:0.02",
              community_benefit: "add:5",
            },
          },
        ],
      },
      {
        id: "cap",
        title: "Capital Allocation",
        description: "Plant age rising 10%+.",
        options: [
          {
            id: "tower",
            label: "Patient Tower",
            icon: "🏗️",
            desc: "Modern facility. Massive capex.",
            effects: {
              beds: "add:80",
              fixed_costs: "add:18000000",
              patient_satisfaction: "add:15",
              quality_score: "add:8",
              market_share: "add:0.05",
              occupancy_rate: "add:0.04",
            },
          },
          {
            id: "ambnet",
            label: "Ambulatory Network",
            icon: "🏥",
            desc: "Outpatient clinics. Referral funnel.",
            effects: {
              outpatient_ratio: "add:0.06",
              market_share: "add:0.04",
              fixed_costs: "add:8000000",
              community_benefit: "add:8",
              patient_satisfaction: "add:5",
            },
          },
          {
            id: "debt",
            label: "Debt Reduction",
            icon: "📉",
            desc: "Better ratings, lower interest.",
            effects: {
              fixed_costs: "mult:0.88",
              efficiency_mult: "mult:0.985",
            },
          },
        ],
      },
    ],
  },
];
